name: CI / Lint

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '16'

      - name: Install dependencies
        run: npm run install --frozen-lockfile

      - name: Run TypeScript
        run: npm run lint:tsc

      - name: Format & Lint
        run: npm run lint

      - name: Check for changes
        run: git diff --exit-code HEAD
